# https://github.com/compose-spec/compose-spec/blob/master/spec.md
# https://github.com/docker/awesome-compose/blob/master/official-documentation-samples/wordpress/README.md

services:
    mariadb:
        build: ./requirements/mariadb
        # https://hanseom.tistory.com/251
        # https://seosh817.tistory.com/387
        # https://stackoverflow.com/questions/32230577/how-do-i-define-the-name-of-image-built-with-docker-compose
        image: mariadb:inception
        container_name:  mariadb
        restart: on-failure
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        expose:
            - "3306"
        # dbdata라는 명명된 볼륨을 /var/lib/mysql 디렉토리에 마운트
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - network
    wordpress:
        depends_on:
            - mariadb
        build: ./requirements/wordpress
        image: wordpress:inception
        container_name: wordpress
        restart: on-failure
        environment:
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - WORDPRESS_DB_CHARSET=${WORDPRESS_DB_CHARSET}
            - WORDPRESS_AUTH_KEY=${WORDPRESS_AUTH_KEY}
            - WORDPRESS_SECURE_AUTH_KEY=${WORDPRESS_SECURE_AUTH_KEY}
            - WORDPRESS_LOGGED_IN_KEY=${WORDPRESS_LOGGED_IN_KEY}
            - WORDPRESS_NONCE_KEY=${WORDPRESS_NONCE_KEY}
            - WORDPRESS_AUTH_SALT=${WORDPRESS_AUTH_SALT}
            - WORDPRESS_SECURE_AUTH_SALT=${WORDPRESS_SECURE_AUTH_SALT}
            - WORDPRESS_LOGGED_IN_SALT=${WORDPRESS_LOGGED_IN_SALT}
            - WORDPRESS_NONCE_SALT=${WORDPRESS_NONCE_SALT}
            - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
        expose:
            - "9000"
        volumes:
            - wordpress:/var/www/html
        networks:
            - network
    nginx:
        depends_on:
            - wordpress
        build: ./requirements/nginx
        image: nginx:inception
        container_name: nginx
        restart: on-failure
        environment:
            - DOMAIN_NAME=${DOMAIN_NAME}
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        networks:
            - network

volumes:
    wordpress:
    dbdata:

# https://stackoverflow.com/questions/40905761/how-do-i-mount-a-host-directory-as-a-volume-in-docker-compose
networks:
    network:
        driver: bridge
        driver_opts:
            o: bind
            type: none
            device: /home/seunan/data
